apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: ai-tools
  labels:
    app: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: sidpalas/devops-directive-docker-course-node-backend:{{ nodeBackend.version }}
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: node-backend-database-url
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
