apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: node-backend
  namespace: ai-tools
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ sharedVars.hostName }}`) && PathPrefix(`/api/node`)
      middlewares:
        - name: strip-api-prefixes
      services:
        - kind: Service
          name: node-backend
          port: 3000
          scheme: http
