version: "3"

vars:
  # Use your own Docker hub username and repo name
  IMAGE_REPO: docker.io/evanhuang7/ai-tools-frontend
  IMAGE_TAG: developing

tasks:
  install:
    desc: install dependencies
    cmds:
      - npm install

  run:
    desc: Start react client
    cmds:
      - npm run dev

  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .

  # We need to pass the env values when building the frontend image
  # because Vite replaces "import.meta.env.VITE_*" in code during the build.
  # So we need to set the VITE env var as ARG in "Dockerfile", and
  # pass the values into it when running the cli to build the image.
  # TODO: Remeber to remove after running corresponding to
  # avoid storing it in Github
  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg VITE_CLERK_PUBLISHABLE_KEY=pk_test_aW5zcGlyZWQtZmF3bi0zNS5jbGVyay5hY2NvdW50cy5kZXYk \
        --build-arg VITE_VAPI_PUBLIC_KEY=b099cbfe-44d6-4a99-aa4b-4f112b72b233 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .
