apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: ai-tools
  namespace: kluctl-gitops
spec:
  interval: 5m
  source:
    git:
      url: https://github.com/EvanHuang7/ai-tools.git
      # It will control the deployment of application itself
      # because we define the all resources of app in kluctl folder.
      path: kluctl
  target: staging
  context: default
  # let it automatically clean up orphan KluctlDeployment resources
  prune: true
  delete: true
