# Sepcicy the variables that are shared accross different services.
# such as frontend, go, node, python services share.
# So that, we can reference these shared variables across different manifests.
sharedVars:
  # Note: We don't use it because we didn't set a domain name for app
  hostName: "aitools-prod-evanhuang.duckdns.org"
