# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: node-backend-database-url
  namespace: ai-tools
stringData:
  # TODO: Remeber to remove after running corresponding to
  # avoid storing it in Github
  DATABASE_URL: postgresql://postgres.otuiikhbcyitlgoknrii:Ab12345678!@aws-0-ca-central-1.pooler.supabase.com:6543/postgres
  CLERK_PUBLISHABLE_KEY: pk_test_aW5zcGlyZWQtZmF3bi0zNS5jbGVyay5hY2NvdW50cy5kZXYk
  CLERK_SECRET_KEY: sk_test_OAWZMJyO5yvSoczhFvs23XJtflMVvBpLkS2Cy6qgde
  KAFKA_BOOTSTRAP_SERVER: d1fgarsdfulgj4bj0b60.any.us-west-2.mpx.prd.cloud.redpanda.com:9092
  KAFKA_SASL_USER_PASSWORD: Ab12345678!
  RABBITMQ_URL: amqps://dbxonaxs:y_l5O4IVrUtyyKETGgLSDl4VQcRUm4Sw@moose.rmq.cloudamqp.com/dbxonaxs
