version: "3"

tasks:
  deploy-app-with-gitops-to-staging-cluster:
    desc: "Deploy app and kluctl gitops to staging target/cluster"
    cmds:
      - kluctl deploy -t staging

  deploy-app-with-gitops-to-production-cluster:
    desc: "Deploy app and kluctl gitops to production target/cluster"
    cmds:
      - kluctl deploy -t production

  get-webui-password:
    desc: "Get password for kluctl web ui admin user"
    cmds:
      - kubectl -n kluctl-system get secret webui-secret -o jsonpath='{.data.admin-password}' | base64 -d

  port-forward-webui:
    desc: "Port forward web UI to localhost"
    cmds:
      - kubectl -n kluctl-system port-forward svc/kluctl-webui 8080
