apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
  namespace: ai-tools
  labels:
    app: python-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      # NOTE: This "external-secrets" KSA would be availale only if we
      # deployed external secrets for app services to consume
      serviceAccountName: external-secrets
      containers:
        - name: python-backend
          image: evanhuang7/ai-tools-python-backend:developing
          # K8s will always pull the image from Docker Hub, every time
          # a pod starts even if that the image with this tag already exists on the node.
          # If the tag is ":latest" and "imagePullPolicy" is not set,
          # K8s defaults to use "Always".
          # If the tag is custom like ":developing" or ":v1.0",
          # the default is "IfNotPresent".
          # NOTE: You have to manually pruned old images in your host
          # if running Kind Cluster locally and use "Always" option.
          # In GKE, the node’s kubelet includes automatic image garbage collection
          # so the kubelet will auto clean up unused images for you.
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8088"
          envFrom:
            # NOTE: This "python-backend-secrets" K8s Secret would be availale only if we
            # deployed external secrets for app services to consume
            - secretRef:
                name: python-backend-secrets
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          # We add startupProbe for python app because this app starts up a bit
          # slowly after container starts. K8s will pause the liveness and
          # readiness probes until the startup probe succeeds.
          startupProbe:
            httpGet:
              path: /ping
              port: 8088
            initialDelaySeconds: 0 # Start checking immediately after container starts
            periodSeconds: 5 # Check every 5 seconds
            failureThreshold: 12 # Give it up to 12 tries (12 x 5s = 60s) to succeed
          livenessProbe:
            httpGet:
              path: /ping
              port: 8088
            initialDelaySeconds: 10 # Start checking after container starts running 10s
            periodSeconds: 20 # Check every 20s
            timeoutSeconds: 2 # Fail if API call timeout after 2s
            failureThreshold: 3 # If 3 checks in a row fail, restart the container
          readinessProbe:
            httpGet:
              path: /ping
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              memory: "120Mi"
              cpu: "60m"
            requests:
              memory: "100Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
