# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: go-backend-database-url
  namespace: ai-tools
stringData:
  # Remember to change to your own url
  # Remeber to remove after running corresponding to
  # avoid storing it in Github
  DATABASE_URL: postgresql://neondb_owner:npg_chuXl7Qo2CGv@ep-rapid-rain-a4ztbwzh-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
