# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: go-backend-database-url
  namespace: ai-tools
stringData:
  # TODO: Get the secrets from local ".env" file of "go-backend" folder 
  # and paste it here before deploying app by following "☁️☸️ GKE (GCP): Deploy App in K8s Cluster" section in "README.md" file.
  DATABASE_URL: Secret-Placeholder
  CLERK_SECRET_KEY: Secret-Placeholder
  IMAGEKIT_ID: Secret-Placeholder
  IMAGEKIT_PRIVATE_KEY: Secret-Placeholder
  GOOGLE_API_KEY: Secret-Placeholder
