apiVersion: v1
kind: Service
metadata:
  name: go-backend
  namespace: ai-tools
spec:
  selector:
    app: go-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
