apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: python-backend
  namespace: ai-tools
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      # We can use "sharedVars.hostName" kluctl variable to sepcifcy the
      # host if you set a DNS record for the ExternalIP and your own domain
      match: PathPrefix(`/api/python`)
      middlewares:
        - name: strip-api-prefixes-python
      services:
        - kind: Service
          name: python-backend
          port: 8088
          scheme: http
