apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  namespace: ai-tools
  labels:
    app: go-backend
spec:
  # prettier-ignore
  replicas: {{ goBackend.replicas }}
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name: go-backend
          image: evanhuang7/ai-tools-go-backend:{{ goBackend.version }}
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8000"
          envFrom:
            - secretRef:
                name: go-backend-database-url
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 10 # Start checking after container starts running 10s
            periodSeconds: 20 # Check every 20s
            timeoutSeconds: 2 # Fail if API call timeout after 2s
            failureThreshold: 3 # If 3 checks in a row fail, restart the container
          readinessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              memory: "120Mi"
              cpu: "60m"
            requests:
              memory: "100Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
