apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefixes
  namespace: ai-tools
spec:
  stripPrefix:
    forceSlash: false
    # Strip path prefix for all incoming requests by ingress controller
    prefixes:
      - /api/node
      - /api/go
      - /api/python
