version: "3"

vars:
  REDIS_URL: ""
  MONGODB_URL: ""
  # Use your own Docker hub username and repo name
  IMAGE_REPO: docker.io/evanhuang7/ai-tools-python-backend
  IMAGE_TAG: developing

tasks:
  create-venv:
    desc: Create virtual environment
    cmds:
      - python3 -m venv venv

  install:
    desc: Install Python dependencies into virtualenv
    deps: [create-venv]
    cmds:
      - . venv/bin/activate && pip install -r requirements.txt

  run:
    desc: Start Flask backend service inside virtualenv
    cmds:
      - |
        . venv/bin/activate && \
        FLASK_APP=run.py \
        FLASK_ENV=development \
        REDIS_URL={{.REDIS_URL}} \
        MONGODB_URL={{.MONGODB_URL}} \
        flask run --reload --host=0.0.0.0 --port=8088

  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .
