vars:
  - file: config/{{ args.environment }}.yaml

deployments:
  - path: namespaces
  # Make sure namespace folder files be executed before third-party folder.
  # You need to install "external secret operator" in "third-party" folder
  # if you want to use external secrets.
  - barrier: true
  - include: third-party
  - barrier: true
  - include: services

# These are K8s labels applied to all resources
commonLabels:
  appName: "ai-tools"
