vars:
  - file: config/{{ args.environment }}.yaml

deployments:
  - path: namespaces
  # Make sure namespace folder files be executed before third-party folder
  # TODO: Consider setting up external secret operator in here too
  - barrier: true
  - include: third-party
  - barrier: true
  - include: services

# These are K8s labels applied to all resources
commonLabels:
  appName: "ai-tools"
