apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ai-tools
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: evanhuang7/ai-tools-frontend:developing
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10 # Start checking after container starts running 10s
            periodSeconds: 20 # Check every 20s
            timeoutSeconds: 2 # Fail if API call timeout after 2s
            failureThreshold: 3 # If 3 checks in a row fail, restart the container
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              cpu: 60m
              memory: 120Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            # This is a default location nginx will look for config
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-conf
          name: nginx-conf
