# This file is used to tell the external secrets operator where to find the secrets
apiVersion: external-secrets.io/v1beta1
# This is cluster scope. "Kind: SecretStore" is namespace scope
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    # GCP Secret Managr
    gcpsm:
      # GCP project ID
      projectID: steadfast-pivot-462821-p7
