# This file is used to tell the external secrets operator to find
# the secrets from GCP Secret Managr
apiVersion: external-secrets.io/v1beta1
# This is cluster scope, and "Kind: SecretStore" is namespace scope
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    # GCP Secret Managr
    gcpsm:
      # GCP project ID
      projectID: steadfast-pivot-462821-p7
