apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-tools-app-external-secrets
  namespace: external-secrets
spec:
  # External Secrets Operator (ESO) will poll GCP Secret Manager
  # every hour to refresh the Kubernetes Secret.
  refreshInterval: 1h
  # Referencing to "ClusterSecretStore" kind in "ClusterSecretStore.yaml" filee
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    # Name of the secret to be created in the namespace of K8s cluster
    name: k8s-external-secrets-mongodb-url
    creationPolicy: Owner
  # Specify where external secrets operator should find the values for k8s Secret
  data:
    # The key inside the K8s Secret that will hold the value.
    - secretKey: key-k8s
      remoteRef:
        # The name of the secret in GCP Secret Manager
        key: mongodb-url-in-gcpsm
