apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-tools-app-external-secrets
  namespace: external-secrets
spec:
  # External Secrets Operator (ESO) will poll GCP Secret Manager
  # every hour to refresh the Kubernetes Secret.
  refreshInterval: 1h
  # Referencing to "ClusterSecretStore" kind in "ClusterSecretStore.yaml" filee
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    # Set a name for the secret to be created in the namespace of K8s cluster
    name: k8s-secrets-mongodb-url
    creationPolicy: Owner
    # Specify what secrets to get from GCP Secret Manager
  data:
    # Set a key name inside the K8s Secret that will hold the value.
    - secretKey: mongoUri
      remoteRef:
        # The name of the secret in GCP Secret Manager
        key: mongodb-url-in-gcpsm
