apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: python-backend-external-secrets
  namespace: ai-tools
spec:
  # External Secrets Operator (ESO) will poll GCP Secret Manager
  # every hour to refresh the Kubernetes Secret.
  refreshInterval: 1h
  # Referencing to "ClusterSecretStore" kind in "ClusterSecretStore.yaml" filee
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    # Set a name for External Secrets Operator to use when creating or updating
    # a K8s Secret by using K8s ExternalSecret resource in the same namespace.
    name: python-backend-secrets
    creationPolicy: Owner
    # Specify what secrets to get from GCP Secret Manager
  data:
    # Set a key name inside the K8s Secret that will hold the value.
    # Should match the env name in the app code usage
    - secretKey: MONGODB_URL
      remoteRef:
        # The name of the secret in GCP Secret Manager
        key: mongodb-url-in-gcpsm
    - secretKey: REDIS_URL
      remoteRef:
        key: redis-url-in-gcpsm
