apiVersion: v1
# This is a K8s resource, ServiceAccount
kind: ServiceAccount
metadata:
  # The K8s service account’s name
  name: external-secrets
  # The namespace where K8s service account lives
  namespace: ai-tools
  # Annotate the K8s service account with this
  # GCP IAM service account ("external-secrets") email.
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@steadfast-pivot-462821-p7.iam.gserviceaccount.com
