apiVersion: v1
# The ServiceAccount here is a K8s native resource
kind: ServiceAccount
metadata:
  # The K8s serviceAccount’s name
  name: external-secrets
  # The namespace where K8s serviceAccount lives
  namespace: ai-tools
  # Annotate the K8s serviceAccount with this
  # GCP IAM service account ("external-secrets") email.
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@steadfast-pivot-462821-p7.iam.gserviceaccount.com
